name: android_path_provider
description: Flutter plugin for getting Android directories. (Downloads, Movies, Pictures...)
version: 0.3.0
#author: ChunKoo Park <mix1009@gmail.com>
homepage: https://github.com/mix1009/android_path_provider

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.mix1009.android_path_provider
        pluginClass: AndroidPathProviderPlugin
